version: '3.6'

services:
    mysql:
        build:
            context: ./mysql/
        environment:
            MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS}
        restart: always
        networks:
            - yourls_host
        volumes:
         - data_volume:/var/lib/mysql

    yourls:
        build:
            context: ./yourls/
        environment:
            YOURLS_DB_PASS: ${SQL_ROOT_PASS}
            YOURLS_SITE: ${YOURLS_HOSTNAME}:${YOURLS_PORT}
            YOURLS_USER: ${YOURLS_USER}
            YOURLS_PASS: ${YOURLS_PASS}
            YOURLS_URL_CONVERT: 62
            YOURLS_PRIVATE_API: "true"
            YOURLS_UNIQUE_URLS: "false"
        restart: always
        networks: 
            - yourls_host
        ports:
            - ${YOURLS_PORT}:80

networks:
    yourls_host:
volumes:
    data_volume:
